"
" ~postlogic's vimrc
"   -- with tons of stuff borrowed from all over.

" PATHOGEN
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

" Status Line
set statusline=%<%f\ %h%m%r%{fugitive#statusline()}%=%-14.(%l,%c%V%)\ %P

"Functions 'n stuff

if v:progname =~? "evim"
  finish
endif

if v:version >= 700
  try
    setlocal numberwidth=3
  catch
  endtry
endif

iab teh the

if has('gui_running')
    set columns=90
    set lines=40
    set clipboard+=unnamed
    set guioptions+=a
    set guioptions+=c
    set guioptions-=T
    set guioptions-=m
    set guioptions-=l
    set guioptions-=r
    set guioptions-=b
    set guioptions-=R
    set guioptions-=L
    colorscheme darkspectrum
    set guifont=Bitstream\ Vera\ Sans\ Mono\ 9
    "set guifont=Monospace
elseif (&term == 'screen.linux') || (&term =~ '^linux')
    set t_Co=256
    colorscheme railscasts
elseif (&term == 'rxvt-unicode') || (&term =~ '^xterm') || (&term =~ '^screen')
    set t_Co=256
    set mouse=a
    set ttymouse=xterm
    colorscheme railscasts
else
    colorscheme darkspectrum
endif

" Options

set nocompatible
set backspace=indent,eol,start
set nobackup
set history=50
set ruler
set showcmd
set incsearch
set nowrap
set cmdheight=1
set expandtab
set tabstop=4
set shiftwidth=4
set smartindent
set number
set laststatus=2
let html_use_css=1
map Q gq


" Folding
if has("folding")
"    set foldenable
    set nofoldenable
    set foldmethod=indent
    set foldlevel=1
    set foldminlines=5
endif

set wildchar=<tab>
set wildmenu
set wildmode=longest:full,full

if v:version >= 700
    set cursorline
    set completeopt=menu,menuone,longest,preview
    set numberwidth=1
    
    "popup coloring - use mine, not yours
    hi Pmenu ctermbg=2 guibg=darkolivegreen
    hi PmenuSel ctermbg=0 guibg=black
endif

" Plugins

if &t_Co > 2 || has("gui_running")
  syntax on
  "set hlsearch
endif

if has("autocmd")
  filetype plugin indent on
  
  augroup vimrcEx
  au!

  autocmd FileType text setlocal textwidth=78

  autocmd BufReadPost *
    \ if line("'\"") > 0 && line("'\"") <= line("$") |
    \   exe "normal g`\"" |
    \ endif

  augroup END
else
  set smartindent
endif

filetype plugin on
set ofu=syntaxcomplete#Complete

if hlexists("ExtraWhitespace")
    match ExtraWhitespace /\s\+$/
endif

set enc=utf-8

" perl-support variables
let g:Perl_LocalTemplateFile  = $HOME.'/.vim/bundle/perl-support/perl-support/templates/Templates'
let g:Perl_PerlTags           = 'disabled'

" NERD Tree options
let NERDTreeShowFiles=1
let NERDTreeShowHidden=1
let NERDTreeHighlightCursorline=1
let NERDTreeMouseMode=2

" Key mappings
map <F2> :Gitv<Return>
map <F3> :NERDTreeToggle<Return>
map <F4> :Tlist<Return>
map <F5> :sh<Return>
map <F9> :!./%<Return>

nmap <Leader>nt   :NERDTreeToggle<Return>

" Gitv + Fugitive launch mappings
nmap <Leader>gl   :Gitv<Return>
nmap <Leader>gf   :Gitv!<Return>
nmap <Leader>gst  :Gst<Return>
nmap <Leader>gd   :Gdiff<Return>
nmap <Leader>gb   :Gblame<Return>

" Custom tags
set tags+=~/.tags/perltags

" Tabs + tags
nmap <Leader>t <C-w><C-]><C-w>T

set exrc
set secure

