# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Set to the name theme to load.
# Look in ~/.oh-my-zsh/themes/
export ZSH_THEME="myme"

# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git ssh-agent screen)

export PATH=$HOME/bin:$PATH
source $ZSH/oh-my-zsh.sh

# Customize to your needs...

# Aliases
alias cctags="ctags -f tags --recurse --totals --exclude=blib --exclude=.svn --exclude=.git --exclude='.*.sw*' --extra=q --languages=C"
alias perltags="ctags -f tags --recurse --totals --exclude=blib --exclude=.svn --exclude=.git --exclude='.*.sw*' --extra=q --languages=Perl --langmap=Perl:+.t"

alias ga="git add"
alias gb="git br"
alias gd="git diff"
alias gco="git co"
alias gup="git remote update"
alias gff="git ff"
alias ghi="git hist"
